services:
  - type: web
    name: storie-luce-landing
    runtime: static
    staticPublishPath: .
    branch: main
    buildCommand: echo "no build step"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
